apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: core-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.opengovernance.replicaCount }}
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      serviceAccountName: core
      containers:
      - name: core-service
        image: "{{ .Values.opengovernance.docker.registry }}/core-service:{{ .Values.opengovernance.docker.tags.core }}"
        command: ["/core-service"]
        imagePullPolicy: Always
        #resources:
        #  limits:
        #    cpu: 100m
        #    memory: 500Mi
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        env:
{{- include "elastic.envs" . | indent 8 }}
        - name: CORE_POSTGRES__HOST
          value: "{{ include "postgres.endpoint" . }}"
        - name: CORE_POSTGRES__PORT
          value: "{{ include "postgres.port" . }}"
        - name: CORE_POSTGRES__DB
          value: "core"
        - name: CORE_POSTGRES__USERNAME
          value: "core_service"
        - name: CORE_POSTGRES__PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: coreServiceUserPassword
        - name: CORE_POSTGRES_SSL_MODE
          value: "{{ include "postgres.sslMode" . }}"
        - name: CORE_HTTP__ADDRESS
          value: "0.0.0.0:6251"
        - name: CORE_INTEGRATION__BASE_URL
          value: "http://integration-service.%NAMESPACE%.svc.cluster.local:8000"
        - name: CORE_SCHEDULER__BASE_URL
          value: "http://scheduler.%NAMESPACE%.svc.cluster.local:5251"
        - name: CORE_COMPLIANCE__BASE_URL
          value: "http://compliance-service.%NAMESPACE%.svc.cluster.local:7251"
        - name: CORE_OPENGOVERNANCE_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: CORE_PRIMARY_DOMAIN_URL
          value: "{{ .Values.global.domain }}"
        - name: CORE_DEX_GRPC_ADDR
          value: "{{ .Release.Namespace }}-dex.{{ .Release.Namespace }}.svc.cluster.local:5557"
        - name: CORE_DEX_PUBLIC_CLIENT_REDIRECT_URIS
          value: "https://{{ .Values.global.domain }}/callback,http://{{ .Values.global.domain }}/callback,http://localhost:3000/callback,http://localhost:8080/callback"
        - name: CORE_DEX_PRIVATE_CLIENT_REDIRECT_URIS
          value: "https://{{ .Values.global.domain }}/callback"
        - name: DEX_PUBLIC_CLIENT_REDIRECT_URIS
          value: "https://{{ .Values.global.domain }}/callback,http://{{ .Values.global.domain }}/callback,http://localhost:3000/callback,http://localhost:8080/callback"
        - name: DEX_PRIVATE_CLIENT_REDIRECT_URIS
          value: "https://{{ .Values.global.domain }}/callback"
        - name: CORE_SAMPLEDATA_INTEGRATIONS_CHECK
          value: "494894f0-aa87-4c32-bafd-066c3cf1a6ae,545a3e48-559d-4f1c-a446-27882bf77d68,f36afd2f-cd85-47c6-9eff-be8213289d28,218317b1-6f26-4ad0-91a7-40f17311d5b3,49d89218-1109-4b86-a7a4-edb55aa658dd,79302008-5d35-4a83-914c-20ecd80f4228,e6cb0afa-e624-4ca7-8b47-fa9988831137,1c2a6b18-ac87-4f5e-a472-1e26f8704f29,c00bb650-f448-41b7-8ccc-bcd6184f78c3"
        - name: CORE_VAULT__PROVIDER
          value: {{ .Values.opengovernance.vault.provider }}
        - name: CORE_VAULT__AWS__REGION
          value: {{ .Values.opengovernance.vault.aws.region }}
        - name: CORE_VAULT__AWS__ROLE_ARN
          value: {{ .Values.opengovernance.vault.aws.roleArn }}
        - name: CORE_VAULT__AWS__ACCESS_KEY
          value: {{ .Values.opengovernance.vault.aws.accessKey }}
        - name: CORE_VAULT__AWS__SECRET_KEY
          value: {{ .Values.opengovernance.vault.aws.secretKey }}
        - name: CORE_VAULT__AZURE__BASE_URL
          value: {{ .Values.opengovernance.vault.azure.baseUrl }}
        - name: CORE_VAULT__AZURE__CLIENT_ID
          value: {{ .Values.opengovernance.vault.azure.clientId }}
        - name: CORE_VAULT__AZURE__TENANT_ID
          value: {{ .Values.opengovernance.vault.azure.tenantId }}
        - name: CORE_VAULT__AZURE__CLIENT_SECRET
          value: {{ .Values.opengovernance.vault.azure.clientSecret }}
        - name: CORE_VAULT__HASHICORP__ADDRESS
          value: "http://{{ .Release.Name }}-vault-internal.{{ .Release.Namespace }}.svc.cluster.local:8200"
        - name: CORE_VAULT__KEY_ID
          value: {{ .Values.opengovernance.vault.keyID }}
        - name: STEAMPIPE_HOST
          value: steampipe-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: STEAMPIPE_PORT
          value: "9193"
        - name: STEAMPIPE_USERNAME
          value: "steampipe"
        - name: STEAMPIPE_PASSWORD
          value: "abcd"
        - name: STEAMPIPE_DB
          value: "steampipe"
        - name: HTTP_ADDRESS
          value: "0.0.0.0:6251"
        - name: SCHEDULER_BASE_URL
          value: "http://scheduler.{{ .Release.Namespace }}.svc.cluster.local:5251"
        - name: INTEGRATION_BASE_URL
          value: "http://integration-service.{{ .Release.Namespace }}.svc.cluster.local:8000"
        - name: COMPLIANCE_BASE_URL
          value: "http://compliance-service.{{ .Release.Namespace }}.svc.cluster.local:7251"